/**
 * Kindred — load demo data onto deployed program.
 *
 * Creates the 5 demo orgs, signs federation agreement OAR↔TAR, and registers
 * the 25 synthetic profiles into their respective org buckets.
 *
 * Usage (after `arcium deploy`):
 *   npx ts-node scripts/load-demo-data.ts
 *
 * Requires:
 *   - target/types/kindred.ts (generated by `arcium build`)
 *   - data/synthetic-profiles/profiles.json (generated by data/synthetic-profiles/generate.ts)
 *   - Funded keypair at ~/.config/solana/id.json
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { PublicKey, SystemProgram } from "@solana/web3.js";
import { Kindred } from "../target/types/kindred";
import { randomBytes } from "crypto";
import {
  getArciumEnv,
  getCompDefAccOffset,
  getMXEAccAddress,
  getMempoolAccAddress,
  getCompDefAccAddress,
  getExecutingPoolAccAddress,
  getComputationAccAddress,
  getClusterAccAddress,
  getMXEPublicKey,
  RescueCipher,
  createPacker,
  x25519,
} from "@arcium-hq/client";
import * as fs from "fs";
import * as os from "os";

const PROFILES = JSON.parse(
  fs.readFileSync("data/synthetic-profiles/profiles.json", "utf-8"),
) as {
  profiles: Array<{ id: string; org: string; alleles: number[]; notes: string }>;
};

const ORGS = [
  "Oregon Adoption Registry",
  "Texas Adoption Registry",
  "Donor-Conceived Network",
  "UNHCR Family Tracing",
  "Diaspora Heritage Foundation",
];

// StrProfile = Pack<[u8; 40]>. createPacker bundles 40 u8s into the 2 BigInt
// containers Arcis expects (320 bits / 213-bit packing budget → 2 chunks), so
// RescueCipher.encrypt returns exactly 2 ciphertext blocks matching
// register_profile(ciphertext_0: [u8;32], ciphertext_1: [u8;32]).
const PROFILE_FIELDS = Array.from({ length: 40 }, (_, i) => ({
  name: `alleles[${i}]`,
  type: { Integer: { signed: false, width: 8 } },
}));
const profilePacker = createPacker<{ alleles: number[] }, { alleles: number[] }>(
  PROFILE_FIELDS,
  "StrProfile",
);

async function main() {
  anchor.setProvider(anchor.AnchorProvider.env());
  const program = anchor.workspace.Kindred as Program<Kindred>;
  const provider = anchor.getProvider() as anchor.AnchorProvider;
  const arciumEnv = getArciumEnv();
  const clusterAccount = getClusterAccAddress(arciumEnv.arciumClusterOffset);
  const owner = readKp(`${os.homedir()}/.config/solana/id.json`);

  // 1. Create 5 orgs
  for (const orgName of ORGS) {
    const orgIdBuf = orgIdFromName(orgName);
    console.log(`Creating org: ${orgName}`);
    const computationOffset = new anchor.BN(randomBytes(8), "hex");
    const orgPda = derivePda(program.programId, "org", orgIdBuf);
    const orgBucketPda = derivePda(program.programId, "org_bucket", orgIdBuf);

    try {
      const sig = await program.methods
        .createOrg(computationOffset, Array.from(orgIdBuf), orgName)
        .accountsPartial({
          payer: owner.publicKey,
          org: orgPda,
          orgBucket: orgBucketPda,
          clusterAccount,
          mxeAccount: getMXEAccAddress(program.programId),
          mempoolAccount: getMempoolAccAddress(arciumEnv.arciumClusterOffset),
          executingPool: getExecutingPoolAccAddress(arciumEnv.arciumClusterOffset),
          computationAccount: getComputationAccAddress(
            arciumEnv.arciumClusterOffset,
            computationOffset,
          ),
          compDefAccount: getCompDefAccAddress(
            program.programId,
            Buffer.from(getCompDefAccOffset("init_org_registry")).readUInt32LE(),
          ),
        })
        .signers([owner])
        .rpc({ skipPreflight: true, commitment: "confirmed" });
      console.log(`  → tx: ${sig}`);
    } catch (e: any) {
      if (String(e).includes("already in use")) {
        console.log(`  → already exists, skipping`);
      } else throw e;
    }
  }

  // 2. Sign federation agreement OAR ↔ TAR
  const oar = derivePda(program.programId, "org", orgIdFromName(ORGS[0]));
  const tar = derivePda(program.programId, "org", orgIdFromName(ORGS[1]));
  const agreement = derivePda(
    program.programId,
    "fed",
    Buffer.concat([oar.toBuffer(), tar.toBuffer()]),
  );
  console.log("\nSigning federation agreement: OAR ↔ TAR");
  try {
    const sig = await program.methods
      .setFederationAgreement(new anchor.BN(Math.floor(Date.now() / 1000) + 86400 * 365))
      .accountsPartial({
        adminA: owner.publicKey,
        adminB: owner.publicKey, // single-keypair demo
        orgA: oar,
        orgB: tar,
        agreement,
        systemProgram: SystemProgram.programId,
      })
      .signers([owner])
      .rpc({ commitment: "confirmed" });
    console.log(`  → tx: ${sig}`);
  } catch (e: any) {
    if (String(e).includes("already in use")) {
      console.log(`  → already signed, skipping`);
    } else throw e;
  }

  // 3. Register all profiles
  const mxePubkey = await getMXEPublicKey(provider, program.programId);
  console.log("\nRegistering profiles");
  for (const p of PROFILES.profiles) {
    const orgName = p.org;
    const orgIdBuf = orgIdFromName(orgName);
    const orgPda = derivePda(program.programId, "org", orgIdBuf);
    const orgBucketPda = derivePda(program.programId, "org_bucket", orgIdBuf);

    // Encrypt profile
    const priv = x25519.utils.randomSecretKey();
    const pub = x25519.getPublicKey(priv);
    const shared = x25519.getSharedSecret(priv, mxePubkey);
    const cipher = new RescueCipher(shared);
    const nonce = randomBytes(16);
    const packed = profilePacker.pack({ alleles: p.alleles });
    if (packed.length !== 2) {
      throw new Error(`expected 2 packed containers, got ${packed.length}`);
    }
    const ciphertext = cipher.encrypt(packed, nonce);
    const c0 = Buffer.from(ciphertext[0]);
    const c1 = Buffer.from(ciphertext[1]);

    console.log(`  ${p.id} → ${orgName}`);

    const computationOffset = new anchor.BN(randomBytes(8), "hex");
    try {
      const sig = await program.methods
        .registerProfile(
          computationOffset,
          Array.from(c0),
          Array.from(c1),
          Array.from(pub),
          new anchor.BN(deserializeLE(nonce).toString()),
          true,  // opt_in_intra
          true,  // opt_in_cross
        )
        .accountsPartial({
          payer: owner.publicKey,
          org: orgPda,
          orgBucket: orgBucketPda,
          clusterAccount,
          mxeAccount: getMXEAccAddress(program.programId),
          mempoolAccount: getMempoolAccAddress(arciumEnv.arciumClusterOffset),
          executingPool: getExecutingPoolAccAddress(arciumEnv.arciumClusterOffset),
          computationAccount: getComputationAccAddress(
            arciumEnv.arciumClusterOffset,
            computationOffset,
          ),
          compDefAccount: getCompDefAccAddress(
            program.programId,
            Buffer.from(getCompDefAccOffset("register_profile")).readUInt32LE(),
          ),
        })
        .signers([owner])
        .rpc({ skipPreflight: true, commitment: "confirmed" });
      console.log(`    tx: ${sig}`);
    } catch (e: any) {
      if (String(e).includes("already in use")) {
        console.log(`    skipped (already registered)`);
      } else {
        console.error(`    ERROR: ${e}`);
      }
    }
  }

  console.log("\n✓ Demo data load complete.");
}

function orgIdFromName(name: string): Buffer {
  const buf = Buffer.alloc(32);
  Buffer.from(name).copy(buf);
  return buf;
}

function derivePda(programId: PublicKey, seed: string, ...keys: Buffer[]): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(seed), ...keys],
    programId,
  )[0];
}

function readKp(path: string): anchor.web3.Keypair {
  return anchor.web3.Keypair.fromSecretKey(
    new Uint8Array(JSON.parse(fs.readFileSync(path, "utf-8"))),
  );
}

function deserializeLE(buf: Buffer): bigint {
  let result = 0n;
  for (let i = buf.length - 1; i >= 0; i--) {
    result = (result << 8n) | BigInt(buf[i]);
  }
  return result;
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
